// Calibrates each licensed real car and motorcycle so the simulation's 0-100 km/h time and top speed match the
// real-world figures in VehicleCatalog (spec.t100 / spec.vmax). Writes src/vehicles/RealCarCalibration.js.
//   node tools/dev/calibrate-cars.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { VehiclePhysics } from '../../src/physics/VehiclePhysics.js';
import { CARS, REAL_CAR_IDS, REAL_BIKE_IDS, realParams, bikeParams } from '../../src/vehicles/VehicleCatalog.js';

const flat = { layout: { groundHeight: () => 0 }, collision: { query: () => [] } };
const DT = 1 / 120;
const C = (o) => ({ throttle: 0, brake: 0, steer: 0, handbrake: 0, nitro: false, ...o });

function run(p, seconds, stopAt100 = false) {
  const v = new VehiclePhysics({ ...p }, flat);
  v.place(0, 0, 0); v.step(DT, C({ throttle: 0.3 }));
  let t100 = null;
  for (let t = 0; t < seconds; t += DT) {
    v.step(DT, C({ throttle: 1 }));
    if (t100 === null && v.s.speed * 3.6 >= 100) { t100 = t; if (stopAt100) break; }
  }
  return { t100: t100 ?? 99, top: v.s.speed * 3.6 };
}
const bisect = (lo, hi, f, iters = 18) => { for (let i = 0; i < iters; i++) { const m = (lo + hi) / 2; if (f(m)) hi = m; else lo = m; } return (lo + hi) / 2; };

const out = {};
for (const id of [...REAL_CAR_IDS, ...REAL_BIKE_IDS]) {
  const car = CARS[id], s = car.spec;
  const base = car.bike ? bikeParams(car) : realParams({ ...car, spec: s, powerOversteer: car.params.powerOversteer, driftAssist: car.params.driftAssist });
  const modern = Math.min(1, Math.max(0, (s.era - 1975) / 45));
  // power stays within a plausible band around the real figure; traction (launchG) absorbs the rest
  const PMIN = 0.75, PMAX = 1.2;
  // bikes: traction and wheelies cap a launch near 1 g
  let launchG = car.bike ? 0.9 : s.drive === 'AWD' ? 0.95 + modern * 0.3 : 0.8 + modern * 0.25;
  let power = 1;
  for (let tries = 0; tries < 16; tries++) {
    // smallest power factor whose 0-100 is at or under the real figure
    power = bisect(PMIN, PMAX, (f) => run({ ...base, enginePower: base.enginePower * f, launchG }, 12, true).t100 <= s.t100);
    if (power > PMAX - 0.01) launchG += 0.04;
    else if (power < PMIN + 0.01) launchG = Math.max(0.6, launchG - 0.04);
    else break;
  }
  const withPower = { ...base, enginePower: base.enginePower * power, launchG };
  const vmax = bisect(0.8, 1.35, (f) => run({ ...withPower, maxSpeed: base.maxSpeed * f }, 150).top >= s.vmax);
  const check = run({ ...withPower, maxSpeed: base.maxSpeed * vmax }, 150);
  out[id] = { power: +power.toFixed(3), launchG: +launchG.toFixed(2), vmax: +vmax.toFixed(3) };
  console.log(id.padEnd(24), `power x${power.toFixed(2)} launchG ${launchG.toFixed(2)} vmax x${vmax.toFixed(3)} -> t100 ${check.t100.toFixed(2)} (real ${s.t100}) top ${check.top.toFixed(0)} (real ${s.vmax})`);
}
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
fs.writeFileSync(path.join(root, 'src/vehicles/RealCarCalibration.js'),
  `// Generated by tools/dev/calibrate-cars.mjs — per-car factors so simulated 0-100 km/h and top speed\n// match the real-world figures. Re-run after changing VehiclePhysics or the real specs.\nexport const CALIBRATION = ${JSON.stringify(out, null, 2)};\n`);
console.log('wrote src/vehicles/RealCarCalibration.js');
