// Generated by tools/dev/calibrate-cars.mjs — per-car factors so simulated 0-100 km/h and top speed
// match the real-world figures. Re-run after changing VehiclePhysics or the real specs.
export const CALIBRATION = {
  "bmw_m3_e30": {
    "power": 0.75,
    "launchG": 0.6,
    "vmax": 1.065
  },
  "subaru_wrx_sti_gc8": {
    "power": 0.764,
    "launchG": 0.79,
    "vmax": 1.054
  },
  "mazda_rx7_fd": {
    "power": 0.81,
    "launchG": 0.89,
    "vmax": 1.057
  },
  "porsche_930_turbo": {
    "power": 0.825,
    "launchG": 0.6,
    "vmax": 1.052
  },
  "nissan_skyline_r34": {
    "power": 0.771,
    "launchG": 0.91,
    "vmax": 1.057
  },
  "toyota_supra_mk4": {
    "power": 0.971,
    "launchG": 0.91,
    "vmax": 1.054
  },
  "honda_nsx_na1": {
    "power": 0.779,
    "launchG": 0.64,
    "vmax": 1.062
  },
  "bmw_m4_f82": {
    "power": 0.946,
    "launchG": 1.02,
    "vmax": 1.047
  },
  "nissan_gtr_r35": {
    "power": 0.877,
    "launchG": 1.23,
    "vmax": 1.053
  },
  "chevrolet_corvette_c8": {
    "power": 1.119,
    "launchG": 1.05,
    "vmax": 1.044
  },
  "porsche_911_gt3": {
    "power": 0.78,
    "launchG": 0.92,
    "vmax": 1.05
  },
  "audi_r8_v10": {
    "power": 0.783,
    "launchG": 1.09,
    "vmax": 1.047
  },
  "ferrari_f40": {
    "power": 1.2,
    "launchG": 0.79,
    "vmax": 1.041
  },
  "mclaren_senna": {
    "power": 1.2,
    "launchG": 1.04,
    "vmax": 1.035
  },
  "lamborghini_centenario": {
    "power": 0.815,
    "launchG": 1.18,
    "vmax": 1.042
  },
  "lamborghini_huracan_tt": {
    "power": 0.761,
    "launchG": 1.36,
    "vmax": 1.04
  }
};
